### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ceo0x** [ctf0/vscode-terminal-themes#2]
```
- Version: 1.41.1
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:57:51.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Darwin x64 19.2.0
```

- Notes:
  - Im using zsh (default shell on macos > catalina)
  - Im using the ohmyzsh plugin installed too

**Steps to reproduce:**
Install extension on MacOS, went to settings. 
Selected Dracula. saved, restarted VSCode

**Expected behaviour:**
Terminal theme to be changed

**Actual behavior**
Nothing changes

**Comment by ctf0** [comment]
sorry for the delayed response.

am using it on mac too but on Mojave and its working as expected, could u plz check the dev console and report back any errors related to the extension ?
